[default]
teradata_host = 'td2800.corp.tele2.ru'
send_email_from = 'metrics@info.tele2.ru'
hadoop_host = 't2ru-bda-mnp-001.corp.tele2.ru'
hadoop_port = 10000
kerberos_service_name = 'hive'
sasl_auth = 'GSSAPI'

