[default]
teradata_host = 'td2800.corp.tele2.ru'
teradata_driver = '/opt/teradata/client/ODBC_64/lib/tdataodbc_sb64.so'
email_send_from = 'dvv_monitoring@info.tele2.ru'

[development]
email_send_to = 'ekaterina.gruzdova@tele2.ru'

[production]

